version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
  web:
    build: 
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 80:80
    working_dir: /work
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store:
