version: "3.8"
services:
  app:
    build: ./infra/php
  web:
    build: ./infra/nginx
    ports:
      - 80:80
    working_dir: /work
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store:
