version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
    environment:
      - DB_CONNECTION: circle_testing
      - APP_KEY: base64:dmBYeugMdayS+V0UkxSk1tOQRhP1gKHw2iZZJtTRTL0=
      - APP_ENV: testing
      - APP_DEBUG: true
      - DB_DATABASE: laravel_local
    working_directory: ~/ci-demo
    steps:
      - checkout
      - run: 
          name: Update apt-get
          command: sudo apt-get update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/composer.json" }}
            - v1-dependencies-
      - run:
          working_directory: backend
          name: Install PHP libraries
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "backend/composer.json" }}

      - run:
          working_directory: backend
          name: Run PHPUnit
          command: ./vendor/bin/phpunit